"use client";
import Link from "next/link"; import { Search, X } from "lucide-react"; import { useEffect,useMemo,useState } from "react";
import { receivableReference, type FinanceReceivable } from "@/modules/platform-finance/domain/receivables"; import { PlatformFinanceReceivablesService as Service } from "@/services/platform-finance/PlatformFinanceReceivablesService";
type FinanceReceivableStatus = FinanceReceivable["status"];
const money=(n:number,c:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:c}).format(n); const date=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});
const origins:Record<FinanceReceivable["originType"],string>={invoice:"Issued invoice",client_request:"Client payment request",contract_instalment:"Contract instalment"};
const labels:Record<FinanceReceivableStatus,string>={open:"Open",overdue:"Overdue",partially_settled:"Partially Settled",settled:"Settled"}; const tones:Record<FinanceReceivableStatus,string>={open:"is-info",overdue:"is-danger",partially_settled:"is-amber",settled:"is-success"};
export function PlatformFinanceReceivablesPage(){const[rows,setRows]=useState<FinanceReceivable[]>([]);const[selected,setSelected]=useState<FinanceReceivable|null>(null);const[query,setQuery]=useState("");const[status,setStatus]=useState<"all"|FinanceReceivableStatus>("all");const[busy,setBusy]=useState(true);const[error,setError]=useState<string|null>(null);
useEffect(()=>{let cancelled=false;void Service.list().then((data)=>{if(!cancelled){setRows(data);setBusy(false)}}).catch((cause)=>{if(!cancelled){setError(cause instanceof Error?cause.message:"Unable to load receivables.");setBusy(false)}});return()=>{cancelled=true}},[]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter((row)=>(status==="all"||row.status===status)&&(!q||receivableReference(row).toLowerCase().includes(q)||row.counterpartyDisplayName.toLowerCase().includes(q)||(row.description??"").toLowerCase().includes(q)))},[query,rows,status]);
const counts=Object.fromEntries((["open","overdue","partially_settled","settled"] as const).map((value)=>[value,rows.filter((row)=>row.status===value).length])) as Record<FinanceReceivableStatus,number>;const open=rows.filter((row)=>row.outstandingAmount>0).reduce((sum,row)=>sum+row.outstandingAmount,0);const overdue=rows.filter((row)=>row.status==="overdue").reduce((sum,row)=>sum+row.outstandingAmount,0);
return <div className="pf-requests"><header className="pf-ov-header"><div><h1 className="pf-ov-title">Receivables</h1><p className="pf-ov-desc">Amounts customers owe — from issued invoices and from live client billing made outside SentraCore™.</p></div></header>
<section className="pf-req-summary">{[["Open AR",money(open,"NGN")],["Overdue AR",money(overdue,"NGN")],["Partially Settled",counts.partially_settled],["Settled",counts.settled]].map(([label,value])=><article className="pf-req-summary-card" key={label}><p className="pf-req-summary-label">{label}</p><p className="pf-req-summary-value">{value}</p></article>)}</section>
<nav className="pf-req-tabs">{(["all","open","overdue","partially_settled","settled"] as const).map((value)=><button key={value} className={`pf-req-tab ${status===value?"is-active":""}`} onClick={()=>setStatus(value)}>{value==="all"?"All":labels[value]} <span>{value==="all"?rows.length:counts[value]}</span></button>)}</nav>
<div className="pf-req-table-card"><div className="pf-req-toolbar"><label className="pf-req-search"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search reference, description or customer…"/></label></div>{busy?<div className="pf-req-empty">Loading receivables…</div>:null}{error?<p className="pf-form-error">{error}</p>:null}{!busy&&!error?<div className="pf-req-table-wrap"><table className="pf-req-table"><thead><tr><th>Reference</th><th>Customer</th><th>Due Date</th><th>Original</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{filtered.length?filtered.map((row)=><tr key={row.id} onClick={()=>setSelected(row)}><td className="pf-req-primary">{receivableReference(row)}{row.offLedger?<div className="pf-req-drawer-cat">{origins[row.originType]}</div>:null}</td><td>{row.counterpartyDisplayName}</td><td>{row.dueDate?date(row.dueDate):"Not stated"}</td><td className="pf-req-amount-cell">{money(row.originalAmount,row.currency)}</td><td className="pf-req-amount-cell">{money(row.outstandingAmount,row.currency)}</td><td><span className={`pf-req-status ${tones[row.status]}`}>{labels[row.status]}</span></td></tr>):<tr><td colSpan={6}><div className="pf-req-empty">{rows.length?"No records match the current filters.":"Issued invoice obligations will appear here."}</div></td></tr>}</tbody></table></div>:null}</div>
{selected?<div className="pf-drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="pf-req-drawer" onMouseDown={(e)=>e.stopPropagation()}><header className="pf-req-drawer-head"><div><p className="pf-req-drawer-ref">RECEIVABLE</p><h2 className="pf-req-drawer-title">{receivableReference(selected)}</h2><p className="pf-req-drawer-cat">{selected.counterpartyDisplayName}</p></div><button className="pf-link-btn" onClick={()=>setSelected(null)} aria-label="Close"><X size={18}/></button></header><div className="pf-req-drawer-body"><div className="pf-req-drawer-metrics"><div><span>Original</span><strong>{money(selected.originalAmount,selected.currency)}</strong></div><div><span>Outstanding</span><strong>{money(selected.outstandingAmount,selected.currency)}</strong></div><div><span>Available</span><strong>{money(selected.availableToAllocate,selected.currency)}</strong></div></div>{selected.availableToAllocate<selected.outstandingAmount?<section className="pf-req-drawer-section"><p className="pf-req-description">A confirmed receipt is holding {money(selected.outstandingAmount-selected.availableToAllocate,selected.currency)} pending posting.</p></section>:null}{selected.offLedger?<section className="pf-req-drawer-section"><h3>Source</h3><dl className="pf-req-dl"><div><dt>Origin</dt><dd>{origins[selected.originType]}</dd></div><div><dt>Request</dt><dd>{selected.description}</dd></div><div><dt>Client reference</dt><dd>{selected.clientReference}</dd></div><div><dt>Submitted</dt><dd>{selected.submittedOn?date(selected.submittedOn):"Not stated"}</dd></div><div><dt>Client location</dt><dd>{selected.sourceLocation??"Not stated"}</dd></div><div><dt>Latest update</dt><dd>{selected.sourceUpdate??"Not stated"}</dd></div><div><dt>Historical fact</dt><dd>{selected.historicalFactCode?<Link href="/platform-finance/historical-facts">{selected.historicalFactCode}</Link>:"Not linked"}</dd></div><div><dt>Accounting</dt><dd>Off-ledger — no journal. Confirmed receipts settle it.</dd></div><div><dt>Receipts</dt><dd><Link href="/platform-finance/receipts">Open receipts</Link></dd></div></dl></section>:<section className="pf-req-drawer-section"><h3>Source &amp; accounting</h3><dl className="pf-req-dl"><div><dt>Invoice</dt><dd><Link href={`/platform-finance/invoices/${selected.invoiceId}`}>{selected.invoiceReference}</Link></dd></div><div><dt>Journal</dt><dd><Link href={`/platform-finance/accounting/journal/${selected.journalEntryId}`}>View posted journal</Link></dd></div><div><dt>Receipts</dt><dd><Link href="/platform-finance/receipts">Open receipts</Link></dd></div></dl></section>}</div></aside></div>:null}</div>}
