-- FM Phase 2K — schema object verification (read-only). Every row must show ok = true.
with t(name) as (values ('fm_generator_logs'),('fm_energy_readings'),('fm_diesel_usage'),('fm_waste_logs'),('fm_fumigation_logs'),('fm_deep_cleaning_logs'),('fm_consumables_items'),('fm_consumables_updates'))
select 'tables' as check, count(*) = 8 as ok, count(*) as n from information_schema.tables where table_schema='public' and table_name in (select name from t)
union all select 'rls_enabled', bool_and(c.relrowsecurity), count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in (select name from t)
union all select 'no_client_grants', count(*) = 0, count(*) from information_schema.role_table_grants where table_schema='public' and table_name in (select name from t) and grantee in ('anon','authenticated','PUBLIC')
union all select 'service_role_grants', count(distinct table_name) = 8, count(distinct table_name) from information_schema.role_table_grants where table_schema='public' and table_name in (select name from t) and grantee='service_role'
union all select 'no_policies', count(*) = 0, count(*) from pg_policies where schemaname='public' and tablename in (select name from t)
union all select 'derived_columns_generated', count(*) = 3, count(*) from information_schema.columns where table_schema='public' and is_generated='ALWAYS' and ((table_name='fm_generator_logs' and column_name='hours') or (table_name='fm_diesel_usage' and column_name='consumption') or (table_name='fm_consumables_updates' and column_name='closing'))
union all select 'facility_tenant_fks', count(*) = 6, count(*) from pg_constraint where conname in ('fm_diesel_usage_facility_fk','fm_waste_logs_facility_fk','fm_fumigation_logs_facility_fk','fm_deep_cleaning_logs_facility_fk','fm_consumables_items_facility_fk','fm_consumables_updates_facility_fk')
union all select 'consumables_item_facility_consistency', count(*) = 1, count(*) from pg_constraint where conname = 'fm_consumables_updates_item_fk'
union all select 'no_vendor_fk', count(*) = 0, count(*) from pg_constraint where contype='f' and confrelid = 'public.fm_vendors'::regclass
union all select 'no_generator_energy_facility_column', count(*) = 0, count(*) from information_schema.columns where table_schema='public' and table_name in ('fm_generator_logs','fm_energy_readings') and column_name = 'facility_id'
union all select 'unique_codes', count(*) = 8, count(*) from pg_indexes where schemaname='public' and indexname like '%\_org\_code\_uidx' and tablename in (select name from t)
union all select 'empty_or_validated', true, (select count(*) from public.fm_generator_logs) + (select count(*) from public.fm_energy_readings) + (select count(*) from public.fm_diesel_usage) + (select count(*) from public.fm_waste_logs) + (select count(*) from public.fm_fumigation_logs) + (select count(*) from public.fm_deep_cleaning_logs) + (select count(*) from public.fm_consumables_updates);
