import { createAdminClient } from "@/utils/supabase/admin";
import {
  isRecommendationDecisionValue,
  type RecommendationDecisionValue,
} from "@/lib/recommendations/decisions";
import { OperationalEventTypes } from "../taxonomy";
import {
  isActionOutcome,
  type ActionOutcome,
  type ActionSignal,
  type DecisionReadyRecommendation,
} from "./outcome";
import type { OperationalEventConsumer } from "./types";

const GENERATE_ACTION_KEY = "facility.generate_incident_recommendations";
const RISK_ACTION_KEY = "facility.assess_incident_risk";

type DecisionRow = {
  id: string;
  organisation_id: string;
  operational_event_id: string;
  recommendation_action_run_id: string;
  recommendation_id: string;
  decision: RecommendationDecisionValue;
  reason: string | null;
  actor_profile_id: string;
  created_at: string;
};

type ActionRunRow = {
  id: string;
  organisation_id: string;
  operational_event_id: string;
  action_key: string;
  status: string;
  result: unknown;
};

function asNonEmptyString(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function findRecommendationInOutcome(
  result: unknown,
  recommendationId: string
): DecisionReadyRecommendation | null {
  if (!result || typeof result !== "object") return null;
  const root = result as Record<string, unknown>;
  const lists: unknown[] = [];
  if (Array.isArray(root.recommendations)) lists.push(...root.recommendations);
  if (root.data && typeof root.data === "object") {
    const nested = (root.data as Record<string, unknown>).recommendations;
    if (Array.isArray(nested)) lists.push(...nested);
  }

  for (const item of lists) {
    if (!item || typeof item !== "object") continue;
    const rec = item as Record<string, unknown>;
    const id =
      typeof rec.id === "string"
        ? rec.id.trim()
        : typeof rec.key === "string"
          ? rec.key.trim()
          : "";
    if (id !== recommendationId) continue;
    return {
      id,
      priority:
        (rec.priority as DecisionReadyRecommendation["priority"]) ?? "normal",
      title: typeof rec.title === "string" ? rec.title : id,
      description:
        typeof rec.description === "string" ? rec.description : undefined,
      reason: typeof rec.reason === "string" ? rec.reason : "",
      sources: Array.isArray(rec.sources)
        ? (rec.sources as DecisionReadyRecommendation["sources"])
        : [],
      evidence: Array.isArray(rec.evidence)
        ? (rec.evidence as DecisionReadyRecommendation["evidence"])
        : [],
      suggestedAction:
        typeof rec.suggestedAction === "string"
          ? rec.suggestedAction
          : undefined,
    };
  }
  return null;
}

function readRiskLevel(result: unknown): string | null {
  if (!isActionOutcome(result)) return null;
  if (result.status !== "succeeded") return null;
  const level = result.data?.riskLevel;
  return typeof level === "string" && level.trim() ? level.trim() : null;
}

function buildFeedbackSignals(options: {
  decision: RecommendationDecisionValue;
  riskLevel: string | null;
  recommendationId: string;
  recommendationDecisionId: string;
  reason: string | null;
}): ActionSignal[] {
  const {
    decision,
    riskLevel,
    recommendationId,
    recommendationDecisionId,
    reason,
  } = options;

  const baseEvidence: Record<string, unknown> = {
    recommendationId,
    recommendationDecisionId,
    decision,
    riskLevel,
    reason,
  };

  if (decision === "accepted") {
    return [
      {
        key: "recommendation.accepted",
        severity: "info",
        summary:
          "The organisation accepted guidance generated by the Action Engine.",
        evidence: baseEvidence,
      },
    ];
  }

  if (decision === "dismissed" && riskLevel === "critical") {
    return [
      {
        key: "recommendation.critical_risk_dismissed",
        severity: "critical",
        summary:
          "The organisation dismissed guidance generated under a critical risk assessment.",
        evidence: baseEvidence,
      },
    ];
  }

  if (decision === "dismissed" && riskLevel === "high") {
    return [
      {
        key: "recommendation.high_risk_dismissed",
        severity: "warning",
        summary:
          "The organisation dismissed guidance generated under a high risk assessment.",
        evidence: baseEvidence,
      },
    ];
  }

  if (decision === "deferred" && riskLevel === "critical") {
    return [
      {
        key: "recommendation.critical_risk_deferred",
        severity: "warning",
        summary:
          "The organisation deferred guidance generated under a critical risk assessment.",
        evidence: baseEvidence,
      },
    ];
  }

  if (decision === "deferred") {
    return [
      {
        key: "recommendation.deferred",
        severity: "info",
        summary:
          "The organisation deferred Action Engine guidance for later consideration.",
        evidence: baseEvidence,
      },
    ];
  }

  // dismissed with low / moderate / unavailable / unknown
  return [
    {
      key: "recommendation.dismissed",
      severity: "info",
      summary:
        "The organisation dismissed Action Engine guidance.",
      evidence: baseEvidence,
    },
  ];
}

/**
 * Deterministic second-order feedback assessment (Action Engine v1.6).
 * Interprets a specific recommendation_decision against prior intelligence.
 * Does not recalculate risk, signals, or recommendations.
 */
export const assessRecommendationFeedbackConsumer: OperationalEventConsumer =
  async (ctx) => {
    const { event, organisationId, actionKey } = ctx;
    const admin = createAdminClient();

    const decisionId =
      asNonEmptyString(event.entityId) ??
      asNonEmptyString(event.data?.recommendationDecisionId);

    if (!decisionId) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: decision id missing from event.",
        data: {
          actionKey,
          eventId: event.id,
          reason: "missing_decision_id",
        },
        signals: [],
      };
    }

    const { data: decisionRow, error: decisionError } = await admin
      .from("recommendation_decisions")
      .select(
        "id, organisation_id, operational_event_id, recommendation_action_run_id, recommendation_id, decision, reason, actor_profile_id, created_at"
      )
      .eq("id", decisionId)
      .maybeSingle();

    if (decisionError || !decisionRow) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: recommendation decision was not found.",
        data: {
          actionKey,
          eventId: event.id,
          recommendationDecisionId: decisionId,
          reason: "decision_not_found",
          detail: decisionError?.message ?? null,
        },
        signals: [],
      };
    }

    const decision = decisionRow as DecisionRow;

    if (decision.organisation_id !== organisationId) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: organisation boundary mismatch.",
        data: {
          actionKey,
          eventId: event.id,
          recommendationDecisionId: decision.id,
          reason: "organisation_mismatch",
        },
        signals: [],
      };
    }

    if (!isRecommendationDecisionValue(decision.decision)) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: decision value is invalid.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          reason: "invalid_decision_value",
        },
        signals: [],
      };
    }

    const { data: recRun, error: recRunError } = await admin
      .from("action_runs")
      .select(
        "id, organisation_id, operational_event_id, action_key, status, result"
      )
      .eq("id", decision.recommendation_action_run_id)
      .maybeSingle();

    if (recRunError || !recRun) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: recommendation action run was not found.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          recommendationActionRunId: decision.recommendation_action_run_id,
          reason: "recommendation_run_missing",
        },
        signals: [],
      };
    }

    const recommendationRun = recRun as ActionRunRow;

    if (recommendationRun.organisation_id !== organisationId) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: recommendation run organisation mismatch.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          reason: "recommendation_run_org_mismatch",
        },
        signals: [],
      };
    }

    if (
      recommendationRun.operational_event_id !== decision.operational_event_id
    ) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: recommendation run does not belong to the originating operational event.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          reason: "recommendation_run_event_mismatch",
          sourceOperationalEventId: decision.operational_event_id,
          recommendationRunEventId: recommendationRun.operational_event_id,
        },
        signals: [],
      };
    }

    if (recommendationRun.action_key !== GENERATE_ACTION_KEY) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: action run is not a recommendation aggregation run.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          reason: "invalid_recommendation_action_key",
          foundActionKey: recommendationRun.action_key,
        },
        signals: [],
      };
    }

    const matchedRecommendation = findRecommendationInOutcome(
      recommendationRun.result,
      decision.recommendation_id
    );

    if (!matchedRecommendation) {
      return {
        status: "failed",
        summary:
          "Recommendation feedback assessment failed: recommendation_id was not found in the recommendation action outcome.",
        data: {
          actionKey,
          recommendationDecisionId: decision.id,
          recommendationId: decision.recommendation_id,
          reason: "recommendation_not_in_outcome",
        },
        signals: [],
      };
    }

    // Risk assessment for the ORIGINATING incident event (not this decision event).
    const { data: riskRun, error: riskRunError } = await admin
      .from("action_runs")
      .select(
        "id, organisation_id, operational_event_id, action_key, status, result"
      )
      .eq("organisation_id", organisationId)
      .eq("operational_event_id", decision.operational_event_id)
      .eq("action_key", RISK_ACTION_KEY)
      .eq("status", "succeeded")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (riskRunError) {
      console.error(
        "[system.assess_recommendation_feedback] risk run lookup failed",
        { error: riskRunError.message }
      );
    }

    const riskLevel = riskRun ? readRiskLevel(riskRun.result) : null;
    const riskAvailable = riskLevel != null;
    const riskActionRunId = riskRun ? String((riskRun as ActionRunRow).id) : null;

    const signals = buildFeedbackSignals({
      decision: decision.decision,
      riskLevel,
      recommendationId: decision.recommendation_id,
      recommendationDecisionId: decision.id,
      reason: decision.reason,
    });

    const status: ActionOutcome["status"] = riskAvailable
      ? "succeeded"
      : "partial";

    const summary = riskAvailable
      ? `Recorded organisational response (${decision.decision}) to recommendation ${decision.recommendation_id} under ${riskLevel} risk.`
      : `Recorded organisational response (${decision.decision}) to recommendation ${decision.recommendation_id}; risk assessment was unavailable.`;

    const outcome: ActionOutcome = {
      status,
      summary,
      data: {
        actionKey,
        recommendationDecisionId: decision.id,
        recommendationId: decision.recommendation_id,
        decision: decision.decision,
        reason: decision.reason,
        riskLevel,
        riskAvailable,
        sourceRecommendationActionRunId: recommendationRun.id,
        sourceRiskActionRunId: riskActionRunId,
        sourceOperationalEventId: decision.operational_event_id,
        decisionEventId: event.id,
        actorProfileId: decision.actor_profile_id,
        decidedAt: decision.created_at,
        recommendation: {
          id: matchedRecommendation.id,
          title: matchedRecommendation.title,
          priority: matchedRecommendation.priority,
        },
        eventType: OperationalEventTypes.SYSTEM_RECOMMENDATION_DECIDED,
      },
      signals,
    };

    return outcome;
  };
