import { randomBytes } from "node:crypto";
import { ActionError } from "@/lib/actions/errors";
import type { FinanceReceipt, ReceiptAccountingPreview } from "@/modules/platform-finance/domain/receipts";
import { PlatformFinanceRepository } from "@/modules/platform-finance/server/PlatformFinanceRepository";
import { PlatformFinanceFinancialAccountsRepository } from "@/modules/platform-finance/server/PlatformFinanceFinancialAccountsRepository";
import { PlatformFinanceServerService } from "@/modules/platform-finance/server/PlatformFinanceServerService";
import { PlatformFinanceReceivablesServerService } from "@/modules/platform-finance/server/PlatformFinanceReceivablesServerService";
import { createAdminClient } from "@/utils/supabase/admin";

type Actor={organisationId:string;profileId:string};
type AllocationInput={receivableId:string;amount:number};
export class PlatformFinanceReceiptsServerService {
  private repo:PlatformFinanceRepository; private faRepo:PlatformFinanceFinancialAccountsRepository; private accounting:PlatformFinanceServerService;
  constructor(private organisationId:string){this.repo=new PlatformFinanceRepository(organisationId);this.faRepo=new PlatformFinanceFinancialAccountsRepository(organisationId);this.accounting=new PlatformFinanceServerService(organisationId);}
  async capabilities(actor:Actor){const caps=await this.loadCaps(actor.profileId);return{view:caps.has("platform_finance.receipt.view"),record:caps.has("platform_finance.receipt.record"),post:caps.has("platform_finance.receipt.post")&&caps.has("platform_finance.post")};}
  async context(actor:Actor,companyId?:string){await this.require(actor,"platform_finance.receipt.record");const [companies,accounts,receivables]=await Promise.all([this.accounting.listAccessibleCompanies(actor.profileId),this.faRepo.listVisible(actor.profileId,companyId),this.listReceivables(actor,companyId)]);return{companies,accounts:accounts.filter(a=>a.status==="active"),receivables};}
  async list(actor:Actor){await this.require(actor,"platform_finance.receipt.view");const ids=await this.repo.listAccessibleCompanyIds(actor.profileId);if(!ids.length)return[];const {data,error}=await createAdminClient().from("finance_receipts").select("*").eq("organisation_id",this.organisationId).in("company_id",ids).order("receipt_date",{ascending:false});if(error)throw new ActionError("INTERNAL_ERROR",error.message);return Promise.all((data??[]).map(r=>this.detailFromRow(r as Record<string,unknown>)));}
  async get(actor:Actor,id:string){const rows=await this.list(actor);const row=rows.find(r=>r.id===id);if(!row)throw new ActionError("VALIDATION_ERROR","Receipt not found.");return row;}
  async create(actor:Actor,input:{companyId:string;counterpartyId:string;destinationFinancialAccountId:string;externalReference?:string|null;receiptDate:string;currency:string;amount:number;allocations:AllocationInput[]}){await this.require(actor,"platform_finance.receipt.record");const reference=`RCPT-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomBytes(3).toString("hex").toUpperCase()}`;const {data,error}=await createAdminClient().rpc("finance_receipt_create_draft",{p_actor:actor.profileId,p_organisation:this.organisationId,p_company:input.companyId,p_counterparty:input.counterpartyId,p_account:input.destinationFinancialAccountId,p_reference:reference,p_external_reference:input.externalReference??"",p_receipt_date:input.receiptDate,p_currency:input.currency,p_amount:input.amount,p_allocations:input.allocations.map(a=>({receivable_id:a.receivableId,amount:a.amount}))});if(error)throw new ActionError("VALIDATION_ERROR",error.message);return this.get(actor,data as string);}
  async confirm(actor:Actor,id:string){await this.require(actor,"platform_finance.receipt.record");const{error}=await createAdminClient().rpc("finance_receipt_confirm",{p_actor:actor.profileId,p_receipt:id});if(error)throw new ActionError("VALIDATION_ERROR",error.message);return this.get(actor,id);}
  async preview(actor:Actor,id:string):Promise<ReceiptAccountingPreview>{await this.require(actor,"platform_finance.receipt.post");const receipt=await this.get(actor,id);const account=await this.faRepo.getVisible(actor.profileId,receipt.destinationFinancialAccountId);if(!account)throw new ActionError("VALIDATION_ERROR","Destination Financial Account unavailable.");const accounts=await this.repo.listAccounts();const ar=accounts.find(a=>a.code==="1070"&&a.status==="active");if(!ar)throw new ActionError("VALIDATION_ERROR","Trade AR (1070) unavailable.");const period=await this.accounting.findOpenPeriodForDate(receipt.companyId,receipt.receiptDate);return{receipt,debit:{accountId:account.controlGlAccountId,code:account.controlGlAccountCode,name:account.controlGlAccountName},credit:{accountId:ar.id,code:ar.code,name:ar.name},periodId:period?.id??null};}
  async review(actor:Actor,id:string){await this.preview(actor,id);const{error}=await createAdminClient().rpc("finance_receipt_accounting_get_or_create",{p_actor:actor.profileId,p_receipt:id});if(error)throw new ActionError("VALIDATION_ERROR",error.message);return this.preview(actor,id);}
  async post(actor:Actor,id:string){await this.require(actor,"platform_finance.receipt.post");await this.require(actor,"platform_finance.post");const{error}=await createAdminClient().rpc("finance_receipt_post",{p_actor:actor.profileId,p_receipt:id});if(error)throw new ActionError("VALIDATION_ERROR",error.message);return this.get(actor,id);}
  private async listReceivables(actor:Actor,companyId?:string){
    const rows=await new PlatformFinanceReceivablesServerService(this.organisationId).list(actor);
    return rows.filter(row=>!companyId||row.companyId===companyId).map(row=>({id:row.id,company_id:row.companyId,counterparty_id:row.counterpartyId,invoice_reference:row.invoiceReference??row.clientReference,counterparty_display_name:row.counterpartyDisplayName,currency:row.currency,original_amount:row.originalAmount,outstanding_amount:row.outstandingAmount,available_to_allocate:row.availableToAllocate}));
  }
  private async detailFromRow(row:Record<string,unknown>):Promise<FinanceReceipt>{const admin=createAdminClient();const[{data:allocations},{data:ft}]=await Promise.all([admin.from("finance_receipt_allocations").select("id,receivable_id,amount,finance_receivables!inner(invoice_reference,client_reference)").eq("receipt_id",row.id as string),row.finance_transaction_id?admin.from("finance_transactions").select("journal_entry_id").eq("id",row.finance_transaction_id as string).maybeSingle():Promise.resolve({data:null})]);return{id:row.id as string,organisationId:row.organisation_id as string,companyId:row.company_id as string,counterpartyId:row.counterparty_id as string,destinationFinancialAccountId:row.destination_financial_account_id as string,reference:row.reference as string,externalReference:(row.external_reference as string|null)??null,receiptDate:row.receipt_date as string,currency:row.currency as string,amount:Number(row.amount),status:row.status as FinanceReceipt["status"],counterpartyDisplayName:(row.counterparty_display_name as string|null)??null,destinationAccountName:(row.destination_account_name as string|null)??null,destinationAccountLast4:(row.destination_account_last4 as string|null)??null,financeTransactionId:(row.finance_transaction_id as string|null)??null,journalEntryId:(ft?.journal_entry_id as string|null|undefined)??null,allocations:(allocations??[]).map(a=>({id:String(a.id),receivableId:String(a.receivable_id),invoiceReference:(()=>{const r=a.finance_receivables as unknown as {invoice_reference:string|null;client_reference:string|null};return String(r.invoice_reference??r.client_reference??"—")})(),amount:Number(a.amount)})),createdAt:row.created_at as string,confirmedAt:(row.confirmed_at as string|null)??null,postedAt:(row.posted_at as string|null)??null};}
  private async loadCaps(profileId:string){const{data,error}=await createAdminClient().from("finance_capability_grants").select("capability").eq("organisation_id",this.organisationId).eq("profile_id",profileId);if(error)throw new ActionError("INTERNAL_ERROR",error.message);return new Set((data??[]).map(r=>String(r.capability)));}
  private async require(actor:Actor,cap:string){if(actor.organisationId!==this.organisationId||!(await this.loadCaps(actor.profileId)).has(cap))throw new ActionError("FORBIDDEN",`Missing capability ${cap}.`);}
}
